In [2]:
# Dependencie
import pandas as pd

In [4]:
# Load in file
movie_file = "Resources/movie_scores.csv"

In [5]:
# Read and display the CSV with Pandas
movie_file_df = pd.read_csv(movie_file)
movie_file_df

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
0,Avengers: Age of Ultron (2015),74,86,66,7.1,7.8,5.0,4.5,3.70,4.30,...,3.90,3.5,4.5,3.5,3.5,4.0,1330,271107,14846,0.5
1,Cinderella (2015),85,80,67,7.5,7.1,5.0,4.5,4.25,4.00,...,3.55,4.5,4.0,3.5,4.0,3.5,249,65709,12640,0.5
2,Ant-Man (2015),80,90,64,8.1,7.8,5.0,4.5,4.00,4.50,...,3.90,4.0,4.5,3.0,4.0,4.0,627,103660,12055,0.5
3,Do You Believe? (2015),18,84,22,4.7,5.4,5.0,4.5,0.90,4.20,...,2.70,1.0,4.0,1.0,2.5,2.5,31,3136,1793,0.5
4,Hot Tub Time Machine 2 (2015),14,28,29,3.4,5.1,3.5,3.0,0.70,1.40,...,2.55,0.5,1.5,1.5,1.5,2.5,88,19560,1021,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,Mr. Holmes (2015),87,78,67,7.9,7.4,4.0,4.0,4.35,3.90,...,3.70,4.5,4.0,3.5,4.0,3.5,33,7367,1348,0.0
142,'71 (2015),97,82,83,7.5,7.2,3.5,3.5,4.85,4.10,...,3.60,5.0,4.0,4.0,4.0,3.5,60,24116,192,0.0
143,"Two Days, One Night (2014)",97,78,89,8.8,7.4,3.5,3.5,4.85,3.90,...,3.70,5.0,4.0,4.5,4.5,3.5,123,24345,118,0.0
144,Gett: The Trial of Viviane Amsalem (2015),100,81,90,7.3,7.8,3.5,3.5,5.00,4.05,...,3.90,5.0,4.0,4.5,3.5,4.0,19,1955,59,0.0
145,"Kumiko, The Treasure Hunter (2015)",87,63,68,6.4,6.7,3.5,3.5,4.35,3.15,...,3.35,4.5,3.0,3.5,3.0,3.5,19,5289,41,0.0

In [8]:
# List all the columns in the table
movie_file_df.columns

Index(['FILM', 'RottenTomatoes', 'RottenTomatoes_User', 'Metacritic',
       'Metacritic_User', 'IMDB', 'Fandango_Stars', 'Fandango_Ratingvalue',
       'RT_norm', 'RT_user_norm', 'Metacritic_norm', 'Metacritic_user_nom',
       'IMDB_norm', 'RT_norm_round', 'RT_user_norm_round',
       'Metacritic_norm_round', 'Metacritic_user_norm_round',
       'IMDB_norm_round', 'Metacritic_user_vote_count', 'IMDB_user_vote_count',
       'Fandango_votes', 'Fandango_Difference'],
      dtype='object')

In [9]:
# We only want IMDb data, so create a new table that takes the Film and all the columns relating to IMDB
imdb_df = movie_file_df[["IMDB", "IMDB_norm", "IMDB_norm_round", "IMDB_user_vote_count"]]
imdb_df

     IMDB  IMDB_norm  IMDB_norm_round  IMDB_user_vote_count
0     7.8       3.90              4.0                271107
1     7.1       3.55              3.5                 65709
2     7.8       3.90              4.0                103660
3     5.4       2.70              2.5                  3136
4     5.1       2.55              2.5                 19560
..    ...        ...              ...                   ...
141   7.4       3.70              3.5                  7367
142   7.2       3.60              3.5                 24116
143   7.4       3.70              3.5                 24345
144   7.8       3.90              4.0                  1955
145   6.7       3.35              3.5                  5289

[146 rows x 4 columns]

In [11]:
# We only like good movies, so find those that scored over 7, and ignore the norm rating
good_movies = movie_file_df.loc[movie_file_df["IMDB"]>7, ["IMDB_norm", "IMDB_norm_round", "IMDB_user_vote_count"]]
good_movies.head()

   IMDB_norm  IMDB_norm_round  IMDB_user_vote_count
0       3.90              4.0                271107
1       3.55              3.5                 65709
2       3.90              4.0                103660
5       3.60              3.5                 39373
8       3.70              3.5                 12227

In [12]:
# Find less popular movies--i.e., those with fewer than 20K votes
lesspopular_movies = movie_file_df.loc[movie_file_df["IMDB_user_vote_count"]<20000, ["IMDB_norm", "IMDB_norm_round", "IMDB_user_vote_count"]]
lesspopular_movies.head()

   IMDB_norm  IMDB_norm_round  IMDB_user_vote_count
3       2.70              2.5                  3136
4       2.55              2.5                 19560
6       3.45              3.5                  2680
7       3.25              3.5                 16876
8       3.70              3.5                 12227